### PR TITLE
Propagate Logging list arguments

### LINKED ISSUE #2163: logging reading next does not work
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/entry/list.rb#L73-L76

Because none of the instance variables are passed into the from_grpc method, the api responds with an error any time you call next with any parameters:

```
logging = Google::Cloud::Logging.new project_id: project_id
entries = logging.entries(filter:filter_thats_not_null)
entries.next
Google::Cloud::InvalidArgumentError: 3:page_token doesn't match arguments from the request
```

it seems like the from_grpc in the list.next should be called with all the params as https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/project.rb#L152

### PR DESCRIPTION
**Pull request by blowmage**
This change fixes a bug in Logging's list classes. The arguments needed for subsequent list calls would not propagate to the second list object, so the API call for the third list object would raise an error.

[fixes #2163]

### CODE REVIEW

File: google-cloud-logging/lib/google/cloud/logging/metric/list.rb [hunk 1]
```diff
@@ -72,7 +72,7 @@ def next
             return nil unless next?
             ensure_service!
             grpc = @service.list_metrics token: token, max: @max
-            self.class.from_grpc grpc, @service
+            self.class.from_grpc grpc, @service, @max
```
Comment (quartzmo) [inline google-cloud-logging/lib/google/cloud/logging/metric/list.rb]: Want to change the `max` param to keyword arg to match `Entry::List` and `Log::List`?

File: google-cloud-logging/lib/google/cloud/logging/resource_descriptor/list.rb [hunk 2]
```diff
@@ -75,7 +75,7 @@ def next
             list_grpc = @service.list_resource_descriptors(
               token: token, max: @max
             )
-            self.class.from_grpc list_grpc, @service
+            self.class.from_grpc list_grpc, @service, @max
```
Comment (quartzmo) [inline google-cloud-logging/lib/google/cloud/logging/resource_descriptor/list.rb]: Want to change the `max` param to keyword arg to match `Entry::List` and `Log::List`?

File: google-cloud-logging/lib/google/cloud/logging/sink/list.rb [hunk 3]
```diff
@@ -71,7 +71,7 @@ def next
             return nil unless next?
             ensure_service!
             list_grpc = @service.list_sinks token: token, max: @max
-            self.class.from_grpc list_grpc, @service
+            self.class.from_grpc list_grpc, @service, @max
```
Comment (quartzmo) [inline google-cloud-logging/lib/google/cloud/logging/sink/list.rb]: Want to change the `max` param to keyword arg to match `Entry::List` and `Log::List`?

File: google-cloud-logging/lib/google/cloud/logging/metric/list.rb (hunk 1 above)
Comment (blowmage) [reply google-cloud-logging/lib/google/cloud/logging/metric/list.rb]: Possibly, but I don't want to make a change like that in this PR.
