### PR TITLE
Spanner retry for broken streams

### LINKED ISSUE #1236: Resume broken streams
The PartialResultSet object can contain a resume token which can be used to resume a broken stream. The resume token is not guaranteed to be in every message. Results should be buffered until a resume token is present before yielding.

If a stream is broken, a new API request should be made with the token, and results continued to yielded from the new streaming response. If the broken stream cannot be resumed a failure should be raised.

### PR DESCRIPTION
**Pull request by blowmage**
This PR adds retry to streams responses that receive an ABORTED error. Responses are buffered while waiting for a `resume_token`. Values will be returned when the buffer has reached its upper bound.

closes #1236

### CODE REVIEW

File: google-cloud-spanner/lib/google/cloud/spanner/results.rb [hunk 1]
```diff
@@ -85,6 +86,7 @@ def rows
 
           fields = @metadata.row_type.fields
           values = []
+          cached_responses = []
```
Comment (quartzmo) [inline google-cloud-spanner/lib/google/cloud/spanner/results.rb]: Is `cached_responses` bounded somewhere? My understanding is that the buffer should be bounded, and once full, data returned regardless of `resume_token`.

File: google-cloud-spanner/lib/google/cloud/spanner/client.rb [hunk 2]
```diff
@@ -482,12 +482,19 @@ def delete table, *id
...
+        def transaction &block
           ensure_service!
           tx_session = session
           tx_grpc = @project.service.begin_transaction tx_session.path
           tx = Transaction.from_grpc(tx_grpc, tx_session)
-          yield tx
+          begin
+            block.call tx
+          rescue Google::Cloud::AbortedError
+            # Retry the entire transaction
```
Comment (quartzmo) [inline google-cloud-spanner/lib/google/cloud/spanner/client.rb]: I believe this should be performed with a backoff delay, using a value returned by the service?

File: google-cloud-spanner/lib/google/cloud/spanner/service.rb [hunk 3]
```diff
@@ -376,12 +389,10 @@ def inspect
...
         protected
 
-        def default_headers
-          { "google-cloud-resource-prefix" => "projects/#{@project}" }
-        end
-
-        def default_options
-          Google::Gax::CallOptions.new kwargs: default_headers
+        def default_options_from_session session_name
+          default_prefix = session_name.split("/sessions/").first
```
Comment (quartzmo) [inline google-cloud-spanner/lib/google/cloud/spanner/service.rb]: The value of `default_prefix` will be the most specific of database name, instance name, or project name, correct?

File: google-cloud-spanner/lib/google/cloud/spanner/results.rb (hunk 1 above)
Comment (blowmage) [inline google-cloud-spanner/lib/google/cloud/spanner/results.rb]: No, the buffer is not bounded. The requirements document doesn't state how large the buffer should be, or how to measure the buffer size. The node implementation buffers up to 10 responses before responding. I don't see where the python implementation buffers responses. So I left it out for now.

File: google-cloud-spanner/lib/google/cloud/spanner/client.rb (hunk 2 above)
Comment (blowmage) [inline google-cloud-spanner/lib/google/cloud/spanner/client.rb]: I also left this out for now. I haven't been able to observe an ABORTED response from the API, so I don't know for sure how the value will be returned. Also, the grpc client is currently fixing some issues with exposing the trailing metadata.

File: google-cloud-spanner/lib/google/cloud/spanner/service.rb (hunk 3 above)
Comment (blowmage) [inline google-cloud-spanner/lib/google/cloud/spanner/service.rb]: For Data API calls it will always be the database name. In #1237 we are instructed that those are the only calls that require the header.

**Comment by blowmage** [comment]
@quartzmo I have updated this PR with the bounds check matching the node implementation. I have removed the transaction retry and header changes and will re-submit them in separate PRs. Can you please review again?

File: google-cloud-spanner/lib/google/cloud/spanner/results.rb [hunk 4]
```diff
@@ -85,6 +86,8 @@ def rows
 
           fields = @metadata.row_type.fields
           values = []
+          buffered_responses = []
+          buffer_upper_bound = 10
```
Comment (quartzmo) [inline google-cloud-spanner/lib/google/cloud/spanner/results.rb]: Is `10` the best possible value for this bound? I have seen no suggested value in any documentation. I assume you got this from the google-cloud-node implementation since you mention it in the PR description. Is it just a matter of guessing for each platform?

File: google-cloud-spanner/lib/google/cloud/spanner/results.rb [hunk 5]
```diff
@@ -98,24 +101,71 @@ def rows
...
-                grpc.values.unshift merge(chunked_value, grpc.values.shift)
-                chunked_value = nil
-              end
-              to_iterate = values + grpc.values
-              chunked_value = to_iterate.pop if grpc.chunked_value
+              buffered_responses << grpc
+
+              if (grpc.resume_token && grpc.resume_token != "") ||
+                buffered_responses.size >= buffer_upper_bound
+                # This can set the resume_token to nil
```
Comment (quartzmo) [inline google-cloud-spanner/lib/google/cloud/spanner/results.rb]: This is (understandably) involved, and either comments or refactoring to smaller methods with meaningful names will help make it easier to follow. Just adding some comments will be fine for now.

File: google-cloud-spanner/lib/google/cloud/spanner/results.rb (hunk 4 above)
Comment (blowmage) [inline google-cloud-spanner/lib/google/cloud/spanner/results.rb]: This is simply the method used by node. I also haven't seen any direction in the requirements document about how to configure the buffer, or how to determine if its full. Is it the number of requests? Is it the total size of data in the buffer? I don't know.

File: google-cloud-spanner/lib/google/cloud/spanner/results.rb (hunk 5 above)
Comment (blowmage) [inline google-cloud-spanner/lib/google/cloud/spanner/results.rb]: In this specific case I felt a longer, unfactored method was better than implementing the wrong abstraction. It allows for easier changes.

We can't simply break the look up into smaller methods, since it all needs to execute within the same method context because of the Enumerator. It can probably be better, but I'd rather have it working and unfactored now than fully factored sometime in the future.
